OBJECTS_OF_INTEREST = [
    'DRONE', 'CAR', 'TRUCK', 'VEHICLE', 'MILITARY VEHICLE', 'ARMORED VEHICLE',
    'BUILDING', 'HOUSE', 'STRUCTURE', 'ROAD', 'STREET',
    'PERSON', 'HUMAN', 'SOLDIER',
    'WEAPON', 'GUN', 'RIFLE',
    'AIRCRAFT', 'HELICOPTER',
    'TREE', 'VEGETATION',
  
]